image: haskell

variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack"

cache:
  paths:
    - .stack-work
    - .stack

before_script:
  - apt-get update
  - apt-get install -y libsdl2-dev libsdl2-ttf-dev
  - stack setup

test:
  stage: test
  script:
    - stack test --coverage
  artifacts:
    paths:
      - $(stack path --local-hpc-root)

build:
  stage: build
  script:
    - stack build

pages:
  stage: deploy
  dependencies:
    - test
  script:
    - mv $(stack path --local-hpc-root) public
  artifacts:
    paths:
      - public
  only:
    - master
