image: haskell

variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack"

cache:
  paths:
    - .stack-work
    - .stack

before_script:
  - sudo apt-get update
  - apt install libsdl2-dev libsdl2-ttf
  - stack setup

test:
  script:
    - stack test

build:
  script:
    - stack build
